# Pembersihan Outliers

## Data Iris

In [40]:
import pandas as pd
from module.dataTransformer import combineData
from module.fetcher import fetchDataMysql, fetchDataPg

data_pg = fetchDataPg("SELECT petal_length, petal_width, species FROM iris_table")
data_my = fetchDataMysql("SELECT sepal_length, sepal_width FROM iris_table")

iris_df = combineData(data1=data_my, data2=data_pg)
iris_df

    sepal_length sepal_width petal_length petal_width         species
0           5.10        3.50         1.40        0.20     Iris-setosa
1           4.90        3.00         1.40        0.20     Iris-setosa
2           4.70        3.20         1.30        0.20     Iris-setosa
3           4.60        3.10         1.50        0.20     Iris-setosa
4           5.00        3.60         1.40        0.20     Iris-setosa
..           ...         ...          ...         ...             ...
145         6.70        3.00         5.20        2.30  Iris-virginica
146         6.30        2.50         5.00        1.90  Iris-virginica
147         6.50        3.00         5.20        2.00  Iris-virginica
148         6.20        3.40         5.40        2.30  Iris-virginica
149         5.90        3.00         5.10        1.80  Iris-virginica

[150 rows x 5 columns]

In [41]:
# Menyiyngkirkan kolom species (class) 
numeric_iris_df = iris_df[["sepal_length", "sepal_width", "petal_length", "petal_width"]]

## Model ABOD

Membuat model ABOD dengan fraction (proporsi data yang akan di anggap sebagai outlier) sama dengan 0.05 atau 5%

In [42]:
from pycaret.anomaly import *

s = setup(data=numeric_iris_df)

abod_model = create_model("abod", fraction=0.05)

df_abod = assign_model(abod_model)

df_abod

    sepal_length sepal_width petal_length petal_width  Anomaly  Anomaly_Score
0           5.10        3.50         1.40        0.20        0      -0.002695
1           4.90        3.00         1.40        0.20        0      -0.000938
2           4.70        3.20         1.30        0.20        0      -0.005625
3           4.60        3.10         1.50        0.20        0      -0.001406
4           5.00        3.60         1.40        0.20        0      -0.000820
..           ...         ...          ...         ...      ...            ...
145         6.70        3.00         5.20        2.30        1      -0.000195
146         6.30        2.50         5.00        1.90        0      -0.000271
147         6.50        3.00         5.20        2.00        0      -0.000938
148         6.20        3.40         5.40        2.30        0      -0.000316
149         5.90        3.00         5.10        1.80        0      -0.000938

[150 rows x 6 columns]

### Data IRIS clean

Data Tanpa Outliers

In [43]:
clean_iris_abod = df_abod[df_abod["Anomaly"] == 0].merge(iris_df["species"], left_index=True, right_index=True)[["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]]
clean_iris_abod

    sepal_length sepal_width petal_length petal_width         species
0           5.10        3.50         1.40        0.20     Iris-setosa
1           4.90        3.00         1.40        0.20     Iris-setosa
2           4.70        3.20         1.30        0.20     Iris-setosa
3           4.60        3.10         1.50        0.20     Iris-setosa
4           5.00        3.60         1.40        0.20     Iris-setosa
..           ...         ...          ...         ...             ...
144         6.70        3.30         5.70        2.50  Iris-virginica
146         6.30        2.50         5.00        1.90  Iris-virginica
147         6.50        3.00         5.20        2.00  Iris-virginica
148         6.20        3.40         5.40        2.30  Iris-virginica
149         5.90        3.00         5.10        1.80  Iris-virginica

[142 rows x 5 columns]

### Menyimpan File CSV

Download Hasil: [Download data abod_iris_clean.csv](abod_iris_clean.csv)

In [44]:
clean_iris_abod.to_csv("abod_iris_clean.csv")

## Model iforest

Membuat model iforest dengan fraction (proporsi data yang akan di anggap sebagai outlier) sama dengan 0.05 atau 5%

In [45]:
from pycaret.anomaly import *

s = setup(data=numeric_iris_df)

iforest_model = create_model("iforest", fraction=0.05)

df_iforest = assign_model(iforest_model)

df_iforest

    sepal_length sepal_width petal_length petal_width  Anomaly  Anomaly_Score
0           5.10        3.50         1.40        0.20        0      -0.028024
1           4.90        3.00         1.40        0.20        0      -0.030777
2           4.70        3.20         1.30        0.20        0      -0.035469
3           4.60        3.10         1.50        0.20        0      -0.015281
4           5.00        3.60         1.40        0.20        0      -0.025525
..           ...         ...          ...         ...      ...            ...
145         6.70        3.00         5.20        2.30        0      -0.024522
146         6.30        2.50         5.00        1.90        0      -0.020970
147         6.50        3.00         5.20        2.00        0      -0.009199
148         6.20        3.40         5.40        2.30        0      -0.015559
149         5.90        3.00         5.10        1.80        0      -0.035553

[150 rows x 6 columns]

### Data IRIS Clean

Data Tanpa Outliers

In [46]:
clean_iris_iforest = df_iforest[df_iforest["Anomaly"] == 0].merge(iris_df["species"], left_index=True, right_index=True)[["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]]
clean_iris_iforest

    sepal_length sepal_width petal_length petal_width         species
0           5.10        3.50         1.40        0.20     Iris-setosa
1           4.90        3.00         1.40        0.20     Iris-setosa
2           4.70        3.20         1.30        0.20     Iris-setosa
3           4.60        3.10         1.50        0.20     Iris-setosa
4           5.00        3.60         1.40        0.20     Iris-setosa
..           ...         ...          ...         ...             ...
145         6.70        3.00         5.20        2.30  Iris-virginica
146         6.30        2.50         5.00        1.90  Iris-virginica
147         6.50        3.00         5.20        2.00  Iris-virginica
148         6.20        3.40         5.40        2.30  Iris-virginica
149         5.90        3.00         5.10        1.80  Iris-virginica

[142 rows x 5 columns]

### Menyimpan File CSV

Download Hasil: [Download data iforest_iris_clean.csv](iforest_iris_clean.csv)

In [47]:
clean_iris_iforest.to_csv("iforest_iris_clean.csv")

## Model LOF
Membuat model LOF dengan fraction (proporsi data yang akan di anggap sebagai outlier) sama dengan 0.05 atau 5%

In [48]:
from pycaret.anomaly import *

s = setup(data=numeric_iris_df)

lof_model = create_model("lof", fraction=0.05)

df_lof = assign_model(lof_model)

df_lof

    sepal_length sepal_width petal_length petal_width  Anomaly  Anomaly_Score
0           5.10        3.50         1.40        0.20        0       0.997672
1           4.90        3.00         1.40        0.20        0       0.993906
2           4.70        3.20         1.30        0.20        0       1.001341
3           4.60        3.10         1.50        0.20        0       0.992439
4           5.00        3.60         1.40        0.20        0       0.993568
..           ...         ...          ...         ...      ...            ...
145         6.70        3.00         5.20        2.30        0       0.989725
146         6.30        2.50         5.00        1.90        0       1.023798
147         6.50        3.00         5.20        2.00        0       0.992359
148         6.20        3.40         5.40        2.30        0       1.003787
149         5.90        3.00         5.10        1.80        0       0.993543

[150 rows x 6 columns]

### Data IRIS clean

Data Tanpa Outliers

In [49]:
clean_iris_lof = df_lof[df_lof["Anomaly"] == 0].merge(iris_df["species"], left_index=True, right_index=True)[["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]]
clean_iris_lof

    sepal_length sepal_width petal_length petal_width         species
0           5.10        3.50         1.40        0.20     Iris-setosa
1           4.90        3.00         1.40        0.20     Iris-setosa
2           4.70        3.20         1.30        0.20     Iris-setosa
3           4.60        3.10         1.50        0.20     Iris-setosa
4           5.00        3.60         1.40        0.20     Iris-setosa
..           ...         ...          ...         ...             ...
145         6.70        3.00         5.20        2.30  Iris-virginica
146         6.30        2.50         5.00        1.90  Iris-virginica
147         6.50        3.00         5.20        2.00  Iris-virginica
148         6.20        3.40         5.40        2.30  Iris-virginica
149         5.90        3.00         5.10        1.80  Iris-virginica

[142 rows x 5 columns]

### Menyimpan File CSV

Download Hasil: [Download data lof_iris_clean.csv](lof_iris_clean.csv)

In [50]:
clean_iris_lof.to_csv("lof_iris_clean.csv")